### ISSUE TITLE
Depend on psycopg2 rather than psycopg2-binary

### ISSUE THREAD

**Issue by Flamefire** [pepkit/pipestat#106]
Copied from https://github.com/biocommons/hgvs/issues/623 :

The psycopg2 project makes two recommendations in the [psycopg2 vs psycopg2-binary](https://www.psycopg.org/docs/install.html#psycopg-vs-psycopg-binary) docs:

    If you are the maintainer of a published package depending on psycopg2 you shouldn’t use psycopg2-binary as a module dependency.

Secondarily:

    For production use you are advised to use the source distribution.

So could you change to depend on the `psycopg2` instead?

**Comment by nsheff** [comment]
Thanks for raising this. I believe we have run into issues relying on `psycopg2` rather than `psycopg2-binary`, but I can't remember what those were. But given this recommendation, we should look into this and see if we can resolve those.

@khoroshevskyi I think you may have some insight here, can you comment?

**Comment by khoroshevskyi** [comment]
Thanks for mentioning it.
You are right, it's recommended to use `psycopg2` instead of `psycopg2-binary`, especially in production. But on linux, we are often getting error and complication while installing `psycopg2`, that's why we changed it to `psycopg2-binary`

the problem is:
```
Error: pg_config executable not found.

      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:

          python setup.py build_ext --pg-config /path/to/pg_config build ...

      or with the pg_config option in 'setup.cfg'.

      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.

      For further information please check the 'doc/src/install.rst' file (also at
      https://www.psycopg.org/docs/install.html).

```
That's why we decided to use binary version, additionally pipestat is in the early stage of development, that's why it's easier to make manipulations on dependencies.

----
The quick solution to this issue is: 
1) install `pipestat`
2) uninstall `psycopg2-binary`
3) install `psycopg`

---
We will work on this issue, and in future release we will try to change this dependency.

**Comment by nsheff** [comment]
Can we make `psycopg` an 'extra' dependency?

We had previously discussed making the db-backend dependencies optional anyway. I thought we had an issue on that but I can't find it. But anyway, maybe this is a chance to solve the above issue as well. What I think makes the most sense is to:

- make all db-related dependences optional, extra dependencies
- use `psycopg2` instead of `psycopg2-binary` (but have it be optional)
- if whatever we need can't be found, throw an error/warning when using the db backend, with instructions to install either one or the other ?

@donaldcampbelljr I think you have worked on this some, can you comment on the optional dependencies idea?

**Comment by Flamefire** [comment]
Actually that is a deeper issue: You shouldn't depend on `psycopg2-binary` as per the recommendation (and actual incompatibility of that for some platforms where prebuilds are not available) but depending on `psycopg2` always builds from source with other issues/incompatibilities. I'd guess that would need to be solved/answered by the psycopg2 team.

The plan of nsheff sounds good. AFAIK you can have options to install additional dependencies, like `pip install pipestat[foo]` or so. Still not great. So I like the last point: If `import psycopg2` fails, show an error that either of those can be installed.

**Comment by dvarrazzo** [comment]
Hello,

as answered to the OP in the psycopg2 bug tracker, I would propose that you migrate to psycopg 3, which has a less ambiguous support for binary installation and is already supported by SQLAlchemy.

You might or might not want to support the use of extras, e.g. requiring users to `pip install pipestat[postgres]` or `pip install pipestat[binary]`, according to the way you partition the choices of your userbase. Having `psycopg[binary]` in your requirements wouldn't affect other packages requesting psycopg 3 with different extras.

**Comment by donaldcampbelljr** [comment]
To use psycopg3, we would need to use SQL Alchemy 2.0 and, therefore, need to wait for SQLModel to transition to using SQLAlchemy 2.0.

**Comment by nsheff** [comment]
@khoroshevskyi will pipestat 0.6 now rely on psychopg3 (and pydantic2) ?
