### ISSUE TITLE
Add backend specific functions to main pipestat class

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/pipestat#70]
Example:
The `select` function only exists for the dbbackend. When it is called, the user must write `pipestat.backened.select`. It would be better for the user to write `pipestat.select`

**Comment by donaldcampbelljr** [comment]
Accomplished here:
https://github.com/pepkit/pipestat/commit/ee98145d19991823180415cea4721fb0141a84e9

**Comment by nsheff** [comment]
wait, I hadn't realized that this only exists for the dbbackend class... I guess that's why we did it that way, right?

I was thinking these functions should exist for either back-end, and that's why they'd go on the main class...

**Comment by donaldcampbelljr** [comment]
Yes. You are correct. They only exist for the dbbackend. How would you like to proceed? Shall I revert the changes?

**Comment by nsheff** [comment]
I think the prevailing principle should be: The abstract should define an interface that is agnostic to underlying backend type. This is also the rationale behind #74 

Thus, I think these changes should be reverted, and the right answer is that I need to switch and use `.retrieve` instead of `.select`, so I was going about this the wrong way. I've now refactored behost to use `retrieve` and it worked fine, so it was my mistake to suggest we move select up, sorry!

**Comment by donaldcampbelljr** [comment]
Changes reverted. Closing.
