### ISSUE TITLE
Create pipestat iter for dbbackend

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/pipestat#97]
may be useful in tandem with seq col project

**Comment by donaldcampbelljr** [comment]
given filter conditions, returned paged iterator.
pipestat currently has a `dynamic_filter` function which modifies the sql statement before execution.

**Comment by nsheff** [comment]
Here's an implementation of this I wrote for seqcolapi.

https://github.com/refgenie/seqcolapi/blob/91326936f2dcd847ba8be28e703a5c0d77377429/seqcolapi/scconf.py#L24-L68

It may just work to take these functions and stick them on the class in pipestat. Then, it will be an iterable `MutableMapping` with caching.

One thing we should change, though: this code is based on an offset-based pagination. I think we should switch to a cursor-based pagination, which will be more performant -- and in fact, since @donaldcampbelljr already implemented this in pipestat, we should just use that for the 'next page' functionality here.

**Comment by donaldcampbelljr** [comment]
I modified pipestat's iterator to use the cursor position and limit.

It can be used like so:
```
psm_iterable = psm.__iter__(limit=100, cursor=5)

for i in psm_iterable:
   print(i) # prints the record

a = next(psm_iterable)

```
Because pipestat inherits from mutable_mapping, I could only modify `__iter__` and not `__next__`.
